import type { PricingModel, PricingVendor } from '../types'

export const DEFAULT_VENDORS: PricingVendor[] = [
  {
    id: 101,
    name: 'OpenAI',
    icon: 'openai',
    description: 'OpenAI Frontier Models',
  },
  {
    id: 102,
    name: 'Anthropic',
    icon: 'anthropic',
    description: 'Anthropic Claude Series',
  },
  {
    id: 103,
    name: 'DeepSeek',
    icon: 'deepseek',
    description: 'DeepSeek High-Speed Reasoning',
  },
  {
    id: 104,
    name: 'Google',
    icon: 'google',
    description: 'Google Gemini Multimodal',
  },
  {
    id: 105,
    name: 'Meta',
    icon: 'meta',
    description: 'Meta Llama Open Weights',
  },
  {
    id: 106,
    name: 'Mistral',
    icon: 'mistral',
    description: 'Mistral AI Enterprise',
  },
  {
    id: 107,
    name: 'Alibaba',
    icon: 'qwen',
    description: 'Alibaba Qwen Models',
  },
  {
    id: 108,
    name: 'xAI',
    icon: 'xai',
    description: 'xAI Grok Intelligence',
  },
]

export const DEFAULT_FOUNDATION_MODELS: PricingModel[] = [
  // DeepSeek
  {
    id: 2001,
    model_name: 'deepseek-chat',
    description: 'DeepSeek-V3 671B MoE architecture with ultra-high throughput and sub-15ms edge latency.',
    vendor_id: 103,
    vendor_name: 'DeepSeek',
    vendor_icon: 'deepseek',
    quota_type: 0,
    model_ratio: 0.07,
    completion_ratio: 2.0,
    enable_groups: ['default'],
    tags: 'hot,coding,fast,moe',
    supported_endpoint_types: ['openai'],
    context_length: 65536,
    max_output_tokens: 8192,
  },
  {
    id: 2002,
    model_name: 'deepseek-reasoner',
    description: 'DeepSeek-R1 open reasoning model outperforming frontier benchmarks on mathematics and code.',
    vendor_id: 103,
    vendor_name: 'DeepSeek',
    vendor_icon: 'deepseek',
    quota_type: 0,
    model_ratio: 0.275,
    completion_ratio: 4.0,
    enable_groups: ['default'],
    tags: 'hot,flagship,reasoning,math',
    supported_endpoint_types: ['openai'],
    context_length: 65536,
    max_output_tokens: 8192,
  },

  // Anthropic
  {
    id: 2003,
    model_name: 'claude-3-5-sonnet-20241022',
    description: 'Industry-leading intelligence for coding, deep problem-solving, and visual analysis.',
    vendor_id: 102,
    vendor_name: 'Anthropic',
    vendor_icon: 'anthropic',
    quota_type: 0,
    model_ratio: 1.5,
    completion_ratio: 5.0,
    enable_groups: ['default'],
    tags: 'hot,flagship,coding,vision',
    supported_endpoint_types: ['anthropic', 'openai'],
    context_length: 200000,
    max_output_tokens: 8192,
  },
  {
    id: 2004,
    model_name: 'claude-3-5-haiku-20241022',
    description: 'Fastest Claude model offering unmatched speed and code comprehension for instant tasks.',
    vendor_id: 102,
    vendor_name: 'Anthropic',
    vendor_icon: 'anthropic',
    quota_type: 0,
    model_ratio: 0.4,
    completion_ratio: 5.0,
    enable_groups: ['default'],
    tags: 'fast,coding,tools',
    supported_endpoint_types: ['anthropic', 'openai'],
    context_length: 200000,
    max_output_tokens: 8192,
  },
  {
    id: 2005,
    model_name: 'claude-3-opus-20240229',
    description: 'Powerhouse for complex technical synthesis, nuanced writing, and research papers.',
    vendor_id: 102,
    vendor_name: 'Anthropic',
    vendor_icon: 'anthropic',
    quota_type: 0,
    model_ratio: 7.5,
    completion_ratio: 5.0,
    enable_groups: ['default'],
    tags: 'flagship,reasoning,research',
    supported_endpoint_types: ['anthropic', 'openai'],
    context_length: 200000,
    max_output_tokens: 4096,
  },

  // OpenAI
  {
    id: 2006,
    model_name: 'gpt-4o',
    description: 'OpenAI flagship multimodal intelligence supporting native text, vision, and tool calling.',
    vendor_id: 101,
    vendor_name: 'OpenAI',
    vendor_icon: 'openai',
    quota_type: 0,
    model_ratio: 1.25,
    completion_ratio: 4.0,
    enable_groups: ['default'],
    tags: 'hot,flagship,vision,tools',
    supported_endpoint_types: ['openai'],
    context_length: 128000,
    max_output_tokens: 16384,
  },
  {
    id: 2007,
    model_name: 'gpt-4o-mini',
    description: 'Affordable, low-latency small multimodal model optimized for high-volume automation.',
    vendor_id: 101,
    vendor_name: 'OpenAI',
    vendor_icon: 'openai',
    quota_type: 0,
    model_ratio: 0.075,
    completion_ratio: 4.0,
    enable_groups: ['default'],
    tags: 'hot,fast,vision,tools',
    supported_endpoint_types: ['openai'],
    context_length: 128000,
    max_output_tokens: 16384,
  },
  {
    id: 2008,
    model_name: 'o1',
    description: 'Full-scale reinforcement learning reasoning model designed for complex science and math.',
    vendor_id: 101,
    vendor_name: 'OpenAI',
    vendor_icon: 'openai',
    quota_type: 0,
    model_ratio: 7.5,
    completion_ratio: 4.0,
    enable_groups: ['default'],
    tags: 'flagship,reasoning,math',
    supported_endpoint_types: ['openai'],
    context_length: 200000,
    max_output_tokens: 100000,
  },
  {
    id: 2009,
    model_name: 'o3-mini',
    description: 'High-speed reasoning model excelling at complex STEM tasks and multi-file code editing.',
    vendor_id: 101,
    vendor_name: 'OpenAI',
    vendor_icon: 'openai',
    quota_type: 0,
    model_ratio: 0.55,
    completion_ratio: 4.0,
    enable_groups: ['default'],
    tags: 'hot,reasoning,coding',
    supported_endpoint_types: ['openai'],
    context_length: 200000,
    max_output_tokens: 100000,
  },
  {
    id: 2010,
    model_name: 'text-embedding-3-small',
    description: 'High-performance, cost-effective text embeddings for semantic search and RAG retrieval.',
    vendor_id: 101,
    vendor_name: 'OpenAI',
    vendor_icon: 'openai',
    quota_type: 0,
    model_ratio: 0.01,
    completion_ratio: 1.0,
    enable_groups: ['default'],
    tags: 'embeddings,rag',
    supported_endpoint_types: ['embeddings'],
    context_length: 8191,
  },
  {
    id: 2011,
    model_name: 'text-embedding-3-large',
    description: 'Next-generation dense 3072-dimensional embeddings for mission-critical enterprise search.',
    vendor_id: 101,
    vendor_name: 'OpenAI',
    vendor_icon: 'openai',
    quota_type: 0,
    model_ratio: 0.065,
    completion_ratio: 1.0,
    enable_groups: ['default'],
    tags: 'embeddings,rag',
    supported_endpoint_types: ['embeddings'],
    context_length: 8191,
  },
  {
    id: 2012,
    model_name: 'dall-e-3',
    description: 'Highest visual quality image generation model with native prompt refinement.',
    vendor_id: 101,
    vendor_name: 'OpenAI',
    vendor_icon: 'openai',
    quota_type: 1,
    model_ratio: 0,
    completion_ratio: 0,
    model_price: 0.04,
    enable_groups: ['default'],
    tags: 'image,creative',
    supported_endpoint_types: ['image-generation'],
  },

  // Google
  {
    id: 2013,
    model_name: 'gemini-2.0-flash',
    description: 'Google next-generation speed and multimodal model featuring native 1M token context.',
    vendor_id: 104,
    vendor_name: 'Google',
    vendor_icon: 'google',
    quota_type: 0,
    model_ratio: 0.05,
    completion_ratio: 4.0,
    enable_groups: ['default'],
    tags: 'hot,fast,multimodal,1m',
    supported_endpoint_types: ['gemini', 'openai'],
    context_length: 1048576,
    max_output_tokens: 8192,
  },
  {
    id: 2014,
    model_name: 'gemini-2.0-flash-thinking-exp',
    description: 'Experimental reasoning model with transparent chain-of-thought execution.',
    vendor_id: 104,
    vendor_name: 'Google',
    vendor_icon: 'google',
    quota_type: 0,
    model_ratio: 0.05,
    completion_ratio: 4.0,
    enable_groups: ['default'],
    tags: 'reasoning,experimental',
    supported_endpoint_types: ['gemini', 'openai'],
    context_length: 1048576,
    max_output_tokens: 8192,
  },
  {
    id: 2015,
    model_name: 'gemini-1.5-pro',
    description: 'Massive 2 Million token context window for comprehensive codebase and video analysis.',
    vendor_id: 104,
    vendor_name: 'Google',
    vendor_icon: 'google',
    quota_type: 0,
    model_ratio: 0.625,
    completion_ratio: 4.0,
    enable_groups: ['default'],
    tags: 'flagship,multimodal,2m',
    supported_endpoint_types: ['gemini', 'openai'],
    context_length: 2097152,
    max_output_tokens: 8192,
  },

  // Meta
  {
    id: 2016,
    model_name: 'llama-3.3-70b-instruct',
    description: 'Meta frontier open-weights instruction model matching GPT-4o on major benchmarks.',
    vendor_id: 105,
    vendor_name: 'Meta',
    vendor_icon: 'meta',
    quota_type: 0,
    model_ratio: 0.1,
    completion_ratio: 2.0,
    enable_groups: ['default'],
    tags: 'hot,open-source,coding',
    supported_endpoint_types: ['openai'],
    context_length: 128000,
    max_output_tokens: 4096,
  },
  {
    id: 2017,
    model_name: 'llama-3.1-405b-instruct',
    description: 'Flagship 405 Billion parameter open foundation model for enterprise-grade reasoning.',
    vendor_id: 105,
    vendor_name: 'Meta',
    vendor_icon: 'meta',
    quota_type: 0,
    model_ratio: 0.9,
    completion_ratio: 2.0,
    enable_groups: ['default'],
    tags: 'flagship,open-source',
    supported_endpoint_types: ['openai'],
    context_length: 128000,
    max_output_tokens: 4096,
  },
  {
    id: 2018,
    model_name: 'llama-3.1-8b-instruct',
    description: 'Ultra-low-latency 8B model suited for instantaneous edge summaries and classification.',
    vendor_id: 105,
    vendor_name: 'Meta',
    vendor_icon: 'meta',
    quota_type: 0,
    model_ratio: 0.025,
    completion_ratio: 2.0,
    enable_groups: ['default'],
    tags: 'fast,open-source,edge',
    supported_endpoint_types: ['openai'],
    context_length: 128000,
    max_output_tokens: 4096,
  },

  // Mistral
  {
    id: 2019,
    model_name: 'mistral-large-latest',
    description: 'Mistral top-tier reasoning model with sovereign European deployment and multilingual fluency.',
    vendor_id: 106,
    vendor_name: 'Mistral',
    vendor_icon: 'mistral',
    quota_type: 0,
    model_ratio: 1.0,
    completion_ratio: 3.0,
    enable_groups: ['default'],
    tags: 'flagship,reasoning,multilingual',
    supported_endpoint_types: ['openai'],
    context_length: 128000,
    max_output_tokens: 8192,
  },
  {
    id: 2020,
    model_name: 'codestral-latest',
    description: 'State-of-the-art coding generative model trained on 80+ programming languages.',
    vendor_id: 106,
    vendor_name: 'Mistral',
    vendor_icon: 'mistral',
    quota_type: 0,
    model_ratio: 0.15,
    completion_ratio: 3.0,
    enable_groups: ['default'],
    tags: 'coding,fast',
    supported_endpoint_types: ['openai'],
    context_length: 256000,
    max_output_tokens: 8192,
  },

  // Alibaba / Qwen
  {
    id: 2021,
    model_name: 'qwen-2.5-coder-32b-instruct',
    description: 'Benchmark-shattering 32B code model rivaling closed frontier models in SWE-bench.',
    vendor_id: 107,
    vendor_name: 'Alibaba',
    vendor_icon: 'qwen',
    quota_type: 0,
    model_ratio: 0.075,
    completion_ratio: 2.0,
    enable_groups: ['default'],
    tags: 'hot,coding,open-source',
    supported_endpoint_types: ['openai'],
    context_length: 128000,
    max_output_tokens: 8192,
  },
  {
    id: 2022,
    model_name: 'qwen-2.5-72b-instruct',
    description: 'Heavyweight open instruction model excelling at mathematics, reasoning, and agents.',
    vendor_id: 107,
    vendor_name: 'Alibaba',
    vendor_icon: 'qwen',
    quota_type: 0,
    model_ratio: 0.175,
    completion_ratio: 2.0,
    enable_groups: ['default'],
    tags: 'reasoning,open-source',
    supported_endpoint_types: ['openai'],
    context_length: 128000,
    max_output_tokens: 8192,
  },

  // xAI
  {
    id: 2023,
    model_name: 'grok-2',
    description: 'xAI flagship model powered by real-time web awareness and advanced reasoning.',
    vendor_id: 108,
    vendor_name: 'xAI',
    vendor_icon: 'xai',
    quota_type: 0,
    model_ratio: 1.0,
    completion_ratio: 4.0,
    enable_groups: ['default'],
    tags: 'flagship,reasoning,search',
    supported_endpoint_types: ['openai'],
    context_length: 128000,
    max_output_tokens: 8192,
  },
  {
    id: 2024,
    model_name: 'grok-2-vision',
    description: 'High-fidelity visual understanding model with chart and document reasoning capabilities.',
    vendor_id: 108,
    vendor_name: 'xAI',
    vendor_icon: 'xai',
    quota_type: 0,
    model_ratio: 1.0,
    completion_ratio: 4.0,
    enable_groups: ['default'],
    tags: 'vision,multimodal',
    supported_endpoint_types: ['openai'],
    context_length: 128000,
    max_output_tokens: 8192,
  },
]
